version: '3.3'
services:
  db:
    image: postgres:14.0
    volumes:
      - var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  backend:
    image: vasilisa817/backend:latest
    volumes:
      - static_value:/backend/static/
      - media_value:/backend/media/
    depends_on:
      - db
    env_file:
      - ./.env
    restart: always

  frontend:
    image: vasilisa817/frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - static_value:/var/html/static/
      - media_value:/var/html/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - frontend
      - backend
    restart: always

volumes:
  db:
  static_value:
  media_value:
